---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install boto3 as workaround https://github.com/elastic/curator/issues/1496
  pip:
    name: boto3
    version: "<1.16"
  when: ansible_distribution_major_version == "20" and ansible_distribution == "Ubuntu"

- name: Install Elasticsearch Curator via pip.
  pip:
    name: elasticsearch-curator
    version: "{{ elasticsearch_curator_version | default(omit) }}"

- name: Install required dependency.
  pip:
    name: argparse

- name: Ensure configuration directory exists.
  file:
    path: '{{ elasticsearch_curator_config_directory }}'
    state: directory

- name: Write curator.yml and action.yml to configuration directory.
  copy:
    dest: '{{ elasticsearch_curator_config_directory }}/{{ item.file }}'
    content: '{{ item.content }}'
  with_items:
    - file: curator.yml
      content: '{{ elasticsearch_curator_yaml }}'
    - file: action.yml
      content: '{{ elasticsearch_curator_action_yaml }}'

- name: Configure cron jobs for Elasticsearch Curator.
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default('present') }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
    cron_file: "{{ item.cron_file | default('') }}"
    user: "root"
  with_items: "{{ elasticsearch_curator_cron_jobs }}"
